// flow-typed signature: 943c5e1a688cfbded4d4cccc663a2591
// flow-typed version: <<STUB>>/react-native-drawer_v^2.3.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-drawer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-drawer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-drawer/tweener' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-drawer/index' {
  declare module.exports: $Exports<'react-native-drawer'>;
}
declare module 'react-native-drawer/index.js' {
  declare module.exports: $Exports<'react-native-drawer'>;
}
declare module 'react-native-drawer/tweener.js' {
  declare module.exports: $Exports<'react-native-drawer/tweener'>;
}
