// flow-typed signature: 1e2be2e245ce4309a600f1af4bb6d0cc
// flow-typed version: <<STUB>>/react-native-material-cards_vSiDevesh/React-Native-Material-Cards/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-material-cards'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-material-cards' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-material-cards/Card' {
  declare module.exports: any;
}

declare module 'react-native-material-cards/CardAction' {
  declare module.exports: any;
}

declare module 'react-native-material-cards/CardButton' {
  declare module.exports: any;
}

declare module 'react-native-material-cards/CardContent' {
  declare module.exports: any;
}

declare module 'react-native-material-cards/CardImage' {
  declare module.exports: any;
}

declare module 'react-native-material-cards/CardTitle' {
  declare module.exports: any;
}

declare module 'react-native-material-cards/src/index' {
  declare module.exports: any;
}

declare module 'react-native-material-cards/src/Touchable' {
  declare module.exports: any;
}

declare module 'react-native-material-cards/src/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-material-cards/Card.js' {
  declare module.exports: $Exports<'react-native-material-cards/Card'>;
}
declare module 'react-native-material-cards/CardAction.js' {
  declare module.exports: $Exports<'react-native-material-cards/CardAction'>;
}
declare module 'react-native-material-cards/CardButton.js' {
  declare module.exports: $Exports<'react-native-material-cards/CardButton'>;
}
declare module 'react-native-material-cards/CardContent.js' {
  declare module.exports: $Exports<'react-native-material-cards/CardContent'>;
}
declare module 'react-native-material-cards/CardImage.js' {
  declare module.exports: $Exports<'react-native-material-cards/CardImage'>;
}
declare module 'react-native-material-cards/CardTitle.js' {
  declare module.exports: $Exports<'react-native-material-cards/CardTitle'>;
}
declare module 'react-native-material-cards/index' {
  declare module.exports: $Exports<'react-native-material-cards'>;
}
declare module 'react-native-material-cards/index.js' {
  declare module.exports: $Exports<'react-native-material-cards'>;
}
declare module 'react-native-material-cards/src/index.js' {
  declare module.exports: $Exports<'react-native-material-cards/src/index'>;
}
declare module 'react-native-material-cards/src/Touchable.js' {
  declare module.exports: $Exports<'react-native-material-cards/src/Touchable'>;
}
declare module 'react-native-material-cards/src/utils/index.js' {
  declare module.exports: $Exports<'react-native-material-cards/src/utils/index'>;
}
