// flow-typed signature: 05ee522266ce10d133ea87b6b821a0a5
// flow-typed version: <<STUB>>/react-native-firebase_v^3.0.5/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-firebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-firebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-firebase/lib/firebase-app' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/firebase' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/flow' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/internals' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/AdMobComponent' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/AdRequest' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/Banner' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/EventTypes' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/Interstitial' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/NativeExpress' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/RewardedVideo' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/VideoOptions' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/analytics/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/ConfirmationResult' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/PhoneAuthListener' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/EmailAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/FacebookAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/GithubAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/GoogleAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/PhoneAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/TwitterAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/user' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/base' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/config/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/crash/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/disconnect' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/query' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/reference' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/snapshot' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/transaction' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/CollectionReference' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/DocumentChange' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/DocumentReference' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/DocumentSnapshot' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/FieldValue' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/GeoPoint' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/Path' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/Query' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/QuerySnapshot' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/utils/serialize' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/WriteBatch' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/messaging/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/messaging/RemoteMessage' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/perf/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/perf/Trace' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/storage/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/storage/reference' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/storage/task' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/utils/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/emitter/EmitterSubscription' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/emitter/EventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/emitter/EventSubscription' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/emitter/EventSubscriptionVendor' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/log' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/ModuleBase' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/ReferenceBase' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/SyncTree' {
  declare module.exports: any;
}

declare module 'react-native-firebase/scratch' {
  declare module.exports: any;
}

declare module 'react-native-firebase/scripts/rnpm-postlink' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-firebase/index' {
  declare module.exports: $Exports<'react-native-firebase'>;
}
declare module 'react-native-firebase/index.js' {
  declare module.exports: $Exports<'react-native-firebase'>;
}
declare module 'react-native-firebase/lib/firebase-app.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/firebase-app'>;
}
declare module 'react-native-firebase/lib/firebase.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/firebase'>;
}
declare module 'react-native-firebase/lib/flow.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/flow'>;
}
declare module 'react-native-firebase/lib/internals.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/internals'>;
}
declare module 'react-native-firebase/lib/modules/admob/AdMobComponent.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/AdMobComponent'>;
}
declare module 'react-native-firebase/lib/modules/admob/AdRequest.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/AdRequest'>;
}
declare module 'react-native-firebase/lib/modules/admob/Banner.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/Banner'>;
}
declare module 'react-native-firebase/lib/modules/admob/EventTypes.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/EventTypes'>;
}
declare module 'react-native-firebase/lib/modules/admob/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/index'>;
}
declare module 'react-native-firebase/lib/modules/admob/Interstitial.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/Interstitial'>;
}
declare module 'react-native-firebase/lib/modules/admob/NativeExpress.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/NativeExpress'>;
}
declare module 'react-native-firebase/lib/modules/admob/RewardedVideo.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/RewardedVideo'>;
}
declare module 'react-native-firebase/lib/modules/admob/VideoOptions.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/VideoOptions'>;
}
declare module 'react-native-firebase/lib/modules/analytics/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/analytics/index'>;
}
declare module 'react-native-firebase/lib/modules/auth/ConfirmationResult.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/ConfirmationResult'>;
}
declare module 'react-native-firebase/lib/modules/auth/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/index'>;
}
declare module 'react-native-firebase/lib/modules/auth/PhoneAuthListener.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/PhoneAuthListener'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/EmailAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/EmailAuthProvider'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/FacebookAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/FacebookAuthProvider'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/GithubAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/GithubAuthProvider'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/GoogleAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/GoogleAuthProvider'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/PhoneAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/PhoneAuthProvider'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/TwitterAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/TwitterAuthProvider'>;
}
declare module 'react-native-firebase/lib/modules/auth/user.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/user'>;
}
declare module 'react-native-firebase/lib/modules/base.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/base'>;
}
declare module 'react-native-firebase/lib/modules/config/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/config/index'>;
}
declare module 'react-native-firebase/lib/modules/crash/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/crash/index'>;
}
declare module 'react-native-firebase/lib/modules/database/disconnect.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/disconnect'>;
}
declare module 'react-native-firebase/lib/modules/database/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/index'>;
}
declare module 'react-native-firebase/lib/modules/database/query.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/query'>;
}
declare module 'react-native-firebase/lib/modules/database/reference.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/reference'>;
}
declare module 'react-native-firebase/lib/modules/database/snapshot.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/snapshot'>;
}
declare module 'react-native-firebase/lib/modules/database/transaction.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/transaction'>;
}
declare module 'react-native-firebase/lib/modules/firestore/CollectionReference.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/CollectionReference'>;
}
declare module 'react-native-firebase/lib/modules/firestore/DocumentChange.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/DocumentChange'>;
}
declare module 'react-native-firebase/lib/modules/firestore/DocumentReference.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/DocumentReference'>;
}
declare module 'react-native-firebase/lib/modules/firestore/DocumentSnapshot.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/DocumentSnapshot'>;
}
declare module 'react-native-firebase/lib/modules/firestore/FieldValue.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/FieldValue'>;
}
declare module 'react-native-firebase/lib/modules/firestore/GeoPoint.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/GeoPoint'>;
}
declare module 'react-native-firebase/lib/modules/firestore/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/index'>;
}
declare module 'react-native-firebase/lib/modules/firestore/Path.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/Path'>;
}
declare module 'react-native-firebase/lib/modules/firestore/Query.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/Query'>;
}
declare module 'react-native-firebase/lib/modules/firestore/QuerySnapshot.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/QuerySnapshot'>;
}
declare module 'react-native-firebase/lib/modules/firestore/utils/serialize.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/utils/serialize'>;
}
declare module 'react-native-firebase/lib/modules/firestore/WriteBatch.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/WriteBatch'>;
}
declare module 'react-native-firebase/lib/modules/messaging/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/messaging/index'>;
}
declare module 'react-native-firebase/lib/modules/messaging/RemoteMessage.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/messaging/RemoteMessage'>;
}
declare module 'react-native-firebase/lib/modules/perf/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/perf/index'>;
}
declare module 'react-native-firebase/lib/modules/perf/Trace.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/perf/Trace'>;
}
declare module 'react-native-firebase/lib/modules/storage/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/storage/index'>;
}
declare module 'react-native-firebase/lib/modules/storage/reference.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/storage/reference'>;
}
declare module 'react-native-firebase/lib/modules/storage/task.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/storage/task'>;
}
declare module 'react-native-firebase/lib/modules/utils/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/utils/index'>;
}
declare module 'react-native-firebase/lib/utils/emitter/EmitterSubscription.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/emitter/EmitterSubscription'>;
}
declare module 'react-native-firebase/lib/utils/emitter/EventEmitter.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/emitter/EventEmitter'>;
}
declare module 'react-native-firebase/lib/utils/emitter/EventSubscription.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/emitter/EventSubscription'>;
}
declare module 'react-native-firebase/lib/utils/emitter/EventSubscriptionVendor.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/emitter/EventSubscriptionVendor'>;
}
declare module 'react-native-firebase/lib/utils/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/index'>;
}
declare module 'react-native-firebase/lib/utils/log.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/log'>;
}
declare module 'react-native-firebase/lib/utils/ModuleBase.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/ModuleBase'>;
}
declare module 'react-native-firebase/lib/utils/ReferenceBase.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/ReferenceBase'>;
}
declare module 'react-native-firebase/lib/utils/SyncTree.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/SyncTree'>;
}
declare module 'react-native-firebase/scratch.js' {
  declare module.exports: $Exports<'react-native-firebase/scratch'>;
}
declare module 'react-native-firebase/scripts/rnpm-postlink.js' {
  declare module.exports: $Exports<'react-native-firebase/scripts/rnpm-postlink'>;
}
