// flow-typed signature: d261e5943cfe3c77f7864ab363ecb924
// flow-typed version: <<STUB>>/react-native-material-bottom-navigation_v^0.7.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-material-bottom-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-material-bottom-navigation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-material-bottom-navigation/example/ReactNavigationBottomNavigation' {
  declare module.exports: any;
}

declare module 'react-native-material-bottom-navigation/example/SimpleBottomNavigation' {
  declare module.exports: any;
}

declare module 'react-native-material-bottom-navigation/example/StatefulBottomNavigation' {
  declare module.exports: any;
}

declare module 'react-native-material-bottom-navigation/lib/BottomNavigation' {
  declare module.exports: any;
}

declare module 'react-native-material-bottom-navigation/lib/NavigationComponent' {
  declare module.exports: any;
}

declare module 'react-native-material-bottom-navigation/lib/PressRipple' {
  declare module.exports: any;
}

declare module 'react-native-material-bottom-navigation/lib/RippleBackgroundTransition' {
  declare module.exports: any;
}

declare module 'react-native-material-bottom-navigation/lib/Tab' {
  declare module.exports: any;
}

declare module 'react-native-material-bottom-navigation/lib/utils/easing' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-material-bottom-navigation/example/ReactNavigationBottomNavigation.js' {
  declare module.exports: $Exports<'react-native-material-bottom-navigation/example/ReactNavigationBottomNavigation'>;
}
declare module 'react-native-material-bottom-navigation/example/SimpleBottomNavigation.js' {
  declare module.exports: $Exports<'react-native-material-bottom-navigation/example/SimpleBottomNavigation'>;
}
declare module 'react-native-material-bottom-navigation/example/StatefulBottomNavigation.js' {
  declare module.exports: $Exports<'react-native-material-bottom-navigation/example/StatefulBottomNavigation'>;
}
declare module 'react-native-material-bottom-navigation/index' {
  declare module.exports: $Exports<'react-native-material-bottom-navigation'>;
}
declare module 'react-native-material-bottom-navigation/index.js' {
  declare module.exports: $Exports<'react-native-material-bottom-navigation'>;
}
declare module 'react-native-material-bottom-navigation/lib/BottomNavigation.js' {
  declare module.exports: $Exports<'react-native-material-bottom-navigation/lib/BottomNavigation'>;
}
declare module 'react-native-material-bottom-navigation/lib/NavigationComponent.js' {
  declare module.exports: $Exports<'react-native-material-bottom-navigation/lib/NavigationComponent'>;
}
declare module 'react-native-material-bottom-navigation/lib/PressRipple.js' {
  declare module.exports: $Exports<'react-native-material-bottom-navigation/lib/PressRipple'>;
}
declare module 'react-native-material-bottom-navigation/lib/RippleBackgroundTransition.js' {
  declare module.exports: $Exports<'react-native-material-bottom-navigation/lib/RippleBackgroundTransition'>;
}
declare module 'react-native-material-bottom-navigation/lib/Tab.js' {
  declare module.exports: $Exports<'react-native-material-bottom-navigation/lib/Tab'>;
}
declare module 'react-native-material-bottom-navigation/lib/utils/easing.js' {
  declare module.exports: $Exports<'react-native-material-bottom-navigation/lib/utils/easing'>;
}
