// flow-typed signature: b68dca4818bcdd873d2a80bf569ef5dc
// flow-typed version: <<STUB>>/reduxsauce_v0.4.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reduxsauce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reduxsauce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reduxsauce/dist/reduxsauce' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reduxsauce/dist/reduxsauce.js' {
  declare module.exports: $Exports<'reduxsauce/dist/reduxsauce'>;
}
