# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Homeroom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'BatchedBridge',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTActionSheet',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTImage'
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Pods for Homeroom
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'

  pod 'react-native-video', :path => '../node_modules/react-native-video'
  pod 'react-native-mail', :path => '../node_modules/react-native-mail'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
end
