# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Homeroom.xcodeproj")
    match(
      type: "appstore",
      git_url: "https://github.com/nbd9/Homeroom-Certs.git"
    )
    gym(workspace: "Homeroom.xcworkspace", scheme: "Homeroom")
    upload_to_app_store
    slack(message: 'App released to iOS App Store')
  end
end
