# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Homeroom.xcodeproj")
    match(
      type: "appstore",
      git_url: "https://github.com/nbd9/Homeroom-Certs.git"
    )
    gym(workspace: "Homeroom.xcworkspace", scheme: "Homeroom")
    upload_to_app_store
    slack(message: 'App released to iOS App Store')
  end

  desc "Upload a path or minor version to CodePush"
  lane :codepush do
    version = JSON.parse(File.read('../../package.json'))["version"]
    major_version = version.split('.')[0]
    minor_version = version.split('.')[1]

    sh "cd ../.. && appcenter codepush release-react -a nbd9/Support-Seminar --quiet -d Production --env prod --target-binary-version " + major_version + "." + minor_version + ".x --token " + ENV["APPCENTER_TOKEN"]
    slack(message: 'New version released to CodePush')
  end
end
