# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'beta')
    slack(message: 'Beta released to Google Play Store')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
    slack(message: 'App released to Google Play Store')
  end

  desc "Upload a path or minor version to CodePush"
  lane :codepush do
    version = JSON.parse(File.read('../../package.json'))["version"]
    major_version = version.split('.')[0]
    minor_version = version.split('.')[1]
    sh "cd ../.. && appcenter codepush release-react -a nbd9/Support-Seminar-Android --quiet -d Production --env prod --target-binary-version " + major_version + "." + minor_version + ".x --token " + ENV["APPCENTER_TOKEN"]
    slack(message: 'New version released to CodePush')
  end
end
